---
- name: Check if EPEL repository is already installed
  stat:
    path: "{{ awx_server_epel_repofile_path }}"
  register: epel_repofile

- name: Install EPEL repository
  include_tasks: epel-repo.yml
  when:
    - not epel_repofile.stat.exists

- name: Disable firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: Disable selinux
  selinux:
    state: disabled
  register: selinux_state
  notify: Reboot server

- meta: flush_handlers

- name: Install AWX system dependencies
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - git
    - gettext
    - docker
    - nodejs
    - npm
    - gcc-c++
    - bzip2

- name: Install AWX Python dependencies
  pip:
    name: docker-py

- name: Start and enable Docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Clone AWX repository (v{{ awx_server_version }})
  git:
    repo: "https://github.com/ansible/awx.git"
    dest: "{{ awx_server_src_dir }}"
    version: "{{ awx_server_version }}"

- name: Start AWX installer (long running)
  shell: >-
    ansible-playbook -i inventory install.yml
  register: sh_awx_installer
  changed_when: >-
    not (
      sh_awx_installer.stdout
      |regex_search('localhost.*ok=13.*changed=6', multiline=True)
    )
  args:
    chdir: "{{ awx_server_src_dir }}/installer"

